<?php header('Content-Type: text/html; charset=utf-8'); ?>
<?php require_once("/var/www/rbarrientos/config/conexion.php");?>

<?php
$query_rs_usuarios = "SELECT 
    u.Usuario_Nombre as usuario,
    u.Usuario_Password as clave,
    u.Estado_Usuario as estado,
    u.ID_Empleado,
    e.id as id_estilo,
    e.nombre as estilo,
    e.descripcion as descripcion,
	e.color_texto_body,
    e.color_texto_navbar,
    e.color_texto_rotulo,
    e.color_texto_botones,
    e.color_texto_detalle,
    e.color_text_boton_primary,
    e.color_boder_boton_primary,
    e.color_sombra_boton_primary,
    e.color_hover_text_boton_primary,
    e.color_hover_border_boton_primary,
    e.color_hover_sombra_boton_primary,
    e.color_text_boton_secondary,
    e.color_boder_boton_secondary,
    e.color_sombra_boton_secondary,
    e.color_hover_text_boton_secondary,
    e.color_hover_border_boton_secondary,
    e.color_hover_sombra_boton_secondary,
    e.color_bg_body,
    e.color_bg_navbar,
    e.color_bg_navbar_dwd,
    e.color_bg_rotulo,
    e.color_bg_linea_botones,
    e.color_bg_detalle as color_bg_detalle,
    e.color_bg_boton_primary,
    e.color_bg_hover_botom_primary,
    e.color_bg_boton_secondary,
    e.color_bg_hover_botom_secondary,
    e.color_link,
    e.color_link_visited,
    e.color_link_hover,
    e.color_link_active,
    e.color_navbar_link,
    e.color_navbar_link_visited,
    e.color_navbar_link_hover,
    e.color_navbar_link_active,
    e.color_navbar_dwd_link,
    e.color_navbar_dwd_link_visited,
    e.color_navbar_dwd_link_hover,
    e.color_navbar_dwd_link_active,
    e.color_footer_link,
    e.color_footer_link_visited,
    e.color_footer_link_hover,
    e.color_footer_link_active,
    e.navbar_font,
    e.body_font
FROM [IHTT_RENOVACIONES_AUTOMATICAS].[dbo].[TB_estilo] e
JOIN [IHTT_USUARIOS].[dbo].[TB_Usuarios] u ON e.[usuario_modificacion] = u.Usuario_Nombre
where  u.Usuario_Nombre=:correo_electronico";
?>