<style>
:root {
--main_color_bg_body:#ffffff;
--main_color_bg_navbar:#65cb90;
--main_color_bg_navbar_dwd:#c5ecd5;
--main_color_bg_rotulo:#c5ecd5;
--main_color_bg_linea_botones:#f1e2d9;
--main_color_bg_detalle:#c1bbb7;
--main_color_bg_boton_primary:RGBA (173, 146, 130 ,0.5 );
--main_color_bg_boton_secundary:#c6c8ca;
--main_color_texto_body:#000000;
--main_color_texto_navbar:#f1e2d9;
--main_color_texto_rotulo:#3f7f5a;
--main_color_texto_botones:#676f74;
--main_color_texto_detalle:#7c6353;
--main_color_boder_boton_primary:#65cb90;
--main_color_hover_boton_primary:#ffffff;
--main_color_border_boton_secundary:#faf8f3;
--main_color_hover_boton_secundary:#6fbed5;
--main_color_link:#58b27e;
--main_color_link_visited:#cb65a0;
--main_color_link_hover:#c5ecd5;
--main_color_link_active:#c5ecd5;
--main_color_navbar_link:#415061;
--main_color_navbar_link_visited:#c5ecd5;
--main_color_navbar_link_hover:#f1e2d9;
--main_color_navbar_link_active:#c5ecd5;
--main_color_navbar_dwd_link:#3f7f5a;
--main_color_navbar_dwd_link_visited:#676f74;
--main_color_navbar_dwd_link_hover:#ad9282;
--main_color_navbar_dwd_link_active:#ad9282;
--main_color_footer_link:#f1e2d9;
--main_color_footer_link_visited:#415061;
--main_color_footer_link_hover:#415061;
--main_color_footer_link_active:#f1e2d9;
--main_navbar_font:#00;
--main_body_font:#00;
--main-logo-bussines: <?php echo $logo;?>;
--main-logo-pie-bussines: <?php echo $appcfg_logo_pie;?>;
} /* Logo aplicación */
</style>
